name: omnisvg
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10

  - pytorch::pytorch==2.3.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision==0.18.0

  - intel-openmp
  - mkl
  - mkl-service

  - blas=1.0=mkl

  - pip:
    - gradio==5.37.0
    - transformers==4.51.3
    - numpy==2.2.6
    - Pillow==10.1.0
    - CairoSVG==2.7.1
    - einops==0.4.1
    - qwen-vl-utils==0.0.11
    - ConfigArgParse==1.7.1
    - PyYAML==6.0.2
    - typing-inspection==0.4.0
    - typing_extensions==4.12.2
    - ipython==8.12.3
    - moviepy==1.0.3
    - shapely==2.0.7
    # - torch==2.3.0
    # - torchvision==0.18.0

    - accelerate==1.12.0
